# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nothing/camera

PRODUCT_COPY_FILES += \
    vendor/nothing/camera/proprietary/system/etc/permissions/NTCamera-google-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/NTCamera-google-permissions.xml \
    vendor/nothing/camera/proprietary/system/etc/permissions/NTCamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/NTCamera-permissions.xml \
    vendor/nothing/camera/proprietary/system/etc/permissions/privapp-permissions-NothingExperience.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-NothingExperience.xml \
    vendor/nothing/camera/proprietary/system/etc/sysconfig/com.nothing.experimental.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/com.nothing.experimental.xml \
    vendor/nothing/camera/proprietary/system/etc/sysconfig/nothing-hiddenapi-package-allowlist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/nothing-hiddenapi-package-allowlist.xml \
    vendor/nothing/camera/proprietary/system_ext/etc/permissions/com.nothing.feature.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.nothing.feature.xml

PRODUCT_PACKAGES += \
    NothingExperience \
    NTCamera
